# -*- coding: utf-8 -*-
"""emerging project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_NzAy6gwKApROLznVz0_76ZNBh8eBJ2
"""

!pip install pandas matplotlib seaborn google-genai reportlab --quiet

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def load_json(path):
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading {path}: {e}")
        return []

astar_logs = load_json('/content/astar_logs.json')
quantum_logs = load_json('/content/quantum_path_logs.json')

astar_df = pd.DataFrame(astar_logs)
quantum_df = pd.DataFrame(quantum_logs)

print("A* shape:", astar_df.shape)
print("Quantum shape:", quantum_df.shape)

quantum_df = quantum_df.rename(columns={
    "quantum_success": "success",
    "quantum_path_length": "path_length",
    "quantum_explored_nodes": "explored_nodes"
})

astar_df['path_length'] = astar_df['path_length'].fillna(0)
quantum_df['path_length'] = quantum_df['path_length'].fillna(0)

astar_df['explored_nodes'] = astar_df['explored_nodes'].fillna(0)
quantum_df['explored_nodes'] = quantum_df['explored_nodes'].fillna(0)

astar_df['success'] = astar_df['success'].astype(int)
quantum_df['success'] = quantum_df['success'].astype(int)

def compute_metrics(df, name):
    return {
        "Algorithm": name,
        "Success Rate": df['success'].mean(),
        "Avg Path Length": df[df['path_length'] > 0]['path_length'].mean(),
        "Avg Explored Nodes": df['explored_nodes'].mean()
    }

astar_metrics = compute_metrics(astar_df, "A*")
quantum_metrics = compute_metrics(quantum_df, "Quantum")

metrics_df = pd.DataFrame([astar_metrics, quantum_metrics])
print(metrics_df)

# Path Length Distribution
plt.figure()
sns.histplot(astar_df['path_length'], kde=True, label="A*", bins=10)
sns.histplot(quantum_df['path_length'], kde=True, label="Quantum", bins=10)
plt.legend()
plt.title("Path Length Distribution")
plt.show()

# Explored Nodes Distribution
plt.figure()
sns.boxplot(data=[astar_df['explored_nodes'], quantum_df['explored_nodes']])
plt.xticks([0,1], ["A*", "Quantum"])
plt.title("Explored Nodes Comparison (Boxplot)")
plt.show()

# Success Rate per Run
plt.figure()
plt.plot(astar_df['success'], label="A*", marker='o')
plt.plot(quantum_df['success'], label="Quantum", marker='x')
plt.legend()
plt.title("Run-wise Success Comparison")
plt.show()

sns.set(style="whitegrid")

# Success Rate
plt.figure()
sns.barplot(x="Algorithm", y="Success Rate", data=metrics_df)
plt.title("Success Rate Comparison")
plt.show()

# Path Length
plt.figure()
sns.barplot(x="Algorithm", y="Avg Path Length", data=metrics_df)
plt.title("Average Path Length")
plt.show()

# Explored Nodes
plt.figure()
sns.barplot(x="Algorithm", y="Avg Explored Nodes", data=metrics_df)
plt.title("Explored Nodes Comparison")
plt.show()

from google import genai

client = genai.Client(api_key="AIzaSyBGmO_47TdwrsW-aC7hLqNS2F_R6fjOwss")

def generate_explanation(metrics_df):
    try:
        failure_info = ""
        try:
            failures = metrics_df[metrics_df["Success Rate"] < 1]
            if len(failures) > 0:
                failure_info = failures.to_string(index=False)
            else:
                failure_info = "No major failures observed."
        except:
            failure_info = "Failure analysis not available."

        prompt = f"""
        You are an advanced AI research assistant.

        Analyze the following experimental results from a Hybrid Classical–Quantum Path Planning system:

        {metrics_df.to_string(index=False)}

        Perform a COMPLETE analysis with the following sections:

        1. Beginner Explanation:
        - Explain results in very simple terms

        2. Technical Analysis:
        - Compare A* vs Quantum approach
        - Discuss determinism vs probabilistic behavior

        3. Key Observations:
        - Highlight important patterns

        4. Failure Analysis:
        - Analyze why failures occur
        - Data:
        {failure_info}

        5. Decision-Making Insight:
        - When should we use A* vs Quantum?
        - Based on obstacle density or environment

        6. Strength of Quantum Approach:
        - Where it can outperform classical

        7. Future Improvements:
        - How to improve hybrid system

        8. Table Comparison:
        - Provide a clean comparison table

        Keep output:
        - Well-structured
        - Clear headings
        - Professional (report-level)
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text
        elif hasattr(response, "candidates") and response.candidates:
            return response.candidates[0].content.parts[0].text
        else:
            return "No response from Gemini."

    except Exception as e:
        return f"Error: {e}"


explanation = generate_explanation(metrics_df)
print(explanation)

def ai_decision_system(obstacle_density):
    try:
        prompt = f"""
        You are an AI system selecting path planning algorithms.

        Given obstacle density = {obstacle_density},

        Choose:
        - A* OR Quantum

        Explain:
        - Why this choice
        - Expected performance

        Keep it concise.
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return getattr(response, "text", "No response")

    except Exception as e:
        return str(e)

print(ai_decision_system(0.25))

def analyze_specific_run(i):
    try:
        a = astar_df.iloc[i]
        q = quantum_df.iloc[i]

        prompt = f"""
        Compare these runs:

        A*:
        Success: {a['success']}
        Path Length: {a['path_length']}
        Explored: {a['explored_nodes']}

        Quantum:
        Success: {q['success']}
        Path Length: {q['path_length']}
        Explored: {q['explored_nodes']}

        Explain:
        - Why results differ
        - Which is better here
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return getattr(response, "text", "No response")

    except Exception as e:
        return str(e)

print(analyze_specific_run(0))

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
import matplotlib.pyplot as plt
import re

def format_llm_text(text):
    if not text:
        return ""

    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"## (.*?)\n", r"<b>\1</b><br/><br/>", text)
    text = text.replace("* ", "• ")
    text = text.replace("\n", "<br/>")
    return text

plt.figure()
metrics_df.plot(x="Algorithm", y="Success Rate", kind="bar", legend=False)
plt.title("Success Rate Comparison")
plt.savefig("success_rate.png")
plt.close()

plt.figure()
metrics_df.plot(x="Algorithm", y="Avg Path Length", kind="bar", legend=False)
plt.title("Average Path Length")
plt.savefig("path_length.png")
plt.close()

plt.figure()
metrics_df.plot(x="Algorithm", y="Avg Explored Nodes", kind="bar", legend=False)
plt.title("Explored Nodes")
plt.savefig("explored_nodes.png")
plt.close()

llm_main = explanation
llm_decision = ai_decision_system(0.25)
llm_run = analyze_specific_run(0)

doc = SimpleDocTemplate("Hybrid_AI_Report.pdf", pagesize=letter)
styles = getSampleStyleSheet()

content = []

content.append(Paragraph("<b>Hybrid Classical–Quantum Path Planning Report</b>", styles["Title"]))
content.append(Spacer(1, 20))

content.append(Paragraph("<b>Metrics Summary</b>", styles["Heading2"]))
content.append(Paragraph(metrics_df.to_string().replace("\n", "<br/>"), styles["Normal"]))
content.append(Spacer(1, 15))

content.append(Paragraph("<b>Visualizations</b>", styles["Heading2"]))
content.append(Spacer(1, 10))

content.append(Image("success_rate.png", width=400, height=250))
content.append(Spacer(1, 10))

content.append(Image("path_length.png", width=400, height=250))
content.append(Spacer(1, 10))

content.append(Image("explored_nodes.png", width=400, height=250))
content.append(Spacer(1, 20))

content.append(Paragraph("<b>LLM Analysis</b>", styles["Heading2"]))
content.append(Paragraph(format_llm_text(llm_main), styles["Normal"]))
content.append(Spacer(1, 20))

content.append(Paragraph("<b>AI Decision System</b>", styles["Heading2"]))
content.append(Paragraph(format_llm_text(llm_decision), styles["Normal"]))
content.append(Spacer(1, 20))

content.append(Paragraph("<b>Per-Run Analysis</b>", styles["Heading2"]))
content.append(Paragraph(format_llm_text(llm_run), styles["Normal"]))
content.append(Spacer(1, 20))

doc.build(content)